[build]
  # Fonksiyonların nerede olduğunu belirtiyoruz (EKSİK OLAN KISIM BUYDU)
  functions = "functions"
  
  # Siteyi derleme komutu
  command = "npm run build"
  
  # Yayına alınacak klasör
  publish = "public"

[[headers]]
  # Tüm dosyalar için CORS izni verelim (Garanti olsun)
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"